### PR TITLE
Allow namespace configuration inside auto_register_paths

### PR DESCRIPTION
**Pull request by sasa-b**
This PR addresses an already open ticket #112

Currently auto register only works for classes in the global namespace, with the changes in this PR `auto_registration_paths` will accept hash maps with path and namespace configuration in addition to the string paths:
```ruby
config.auto_registration_paths += ['app', {path: 'my_lib/persistence', namespace: true/false/'MyLib::Persistence'}]
```
It would be also good if we could refactor the autoloading to allow for different relations, commands and mappers folder names, this would give a lot of flexibility to devs in how they can organise their codebase.

### CODE REVIEW

**Comment by solnic** [comment]
I'm sorry but I don't have time for this gem. You can take over if you want.

**Comment by sasa-b** [comment]
> I'm sorry but I don't have time for this gem. You can take over if you want.

@solnic Hey man, yes I would be interested, I'd give my best 🤝

**Comment by solnic** [comment]
@sasa-b I just sent an invite so feel free to merge this in and do whatever is needed to improve this gem. I'm no longer using it so it's just outside of my mental space 🙂 I can give you permissions to push new releases to rubygems as well, just let me know.

**Comment by sasa-b** [comment]
@solnic Thanks, that would be great if you could give me permissions to push new releases to rubygems, I wanted to release this as a minor version and update the docs a bit! 

I'm going to merge this.

**Pull request merged**
