### PR TITLE
Generalize inferred repository configuration

### PR DESCRIPTION
**Pull request by mjtko**
Second attempt at this.  Now broken down into different methods of inferring a configuration:

Should the default repository not be explicitly configured via an initializer or (potentially, when implemented) `config/rom.yml`, an attempt is made to derive a configuration automatically.

First preference is given to internal Rails database configuration (database.yml), followed by any manually configured ActiveRecord configuration. If neither of those are available, we next try interpreting any available dm-rails (DataMapper) configuration, finally falling back to a DATABASE_URL environment variable.

I think this covers most use cases and gives us a place in which to drop additional inference mechanisms in future.

### CODE REVIEW

**Comment by mjtko** [comment]
This supercedes the (now closed) #26.

**Comment by aflatter** [comment]
@mjtko ActiveRecord supports configuration via the `DATABASE_URL` environment variable, that's why configuration is read from ActiveRecord instead of simply loading `database.yml`.

**Comment by aflatter** [comment]
@mjtko Why load `database.yml` at all? It's available via ActiveRecord, right?

Also I'm scared of having a single hash interpreter for different kinds of ORMs as it will only introduce plenty of special cases and conditionals that are not scoped to a single ORM anymore.

**Comment by mjtko** [comment]
Hi @aflatter -- thanks for the feedback!

> @mjtko ActiveRecord supports configuration via the DATABASE_URL environment variable, that's why configuration is read from ActiveRecord instead of simply loading database.yml.

Sure, but not if you don't have `ActiveRecord`. :smile:  For example, in my case, I have a `database.yml` for local dev and use `DATABASE_URL` in production, but have no `ActiveRecord` involved at either time.  I guess we could say "unless you're using A-R, use an initializer", but I was attempting to try and cover the largest number of configurations.

> @mjtko Why load database.yml at all? It's available via ActiveRecord, right?

Only if you have ActiveRecord! :)  BTW, this code doesn't load `database.yml`, it uses the built-in Rails feature that handles the loading of `database.yml` which I feel is probably a better bet than relying on `ActiveRecord` specifics.  I would say it's this code that'll be used in 90%+ of cases, regardless of ActiveRecord or DataMapper.

> Also I'm scared of having a single hash interpreter for different kinds of ORMs as it will only introduce plenty of special cases and conditionals that are not scoped to a single ORM anymore.

The interpreter/transformer is used in situations where we know the format of the `Hash` -- i.e. it comes out of Rails' guts, or it comes out of ActiveRecord's guts, or DM-Rails's guts.  Not sure why that'd be particularly unsafe.  We could start off with empty subclasses for each ORM, but that seems a little pointless - implement that when needed, otherwise keep it simple IMHO.

Perhaps with some verification that it's the "right kind of Hash" you'd see this as less of an issue?

There are always going to be edge cases, my attempt is to cover as many of the 'main' use cases as possible.  It could be argued that "no ActiveRecord" is an edge case of course! :smile:

I suppose the question this PR raises is "how many configuration methods do we want to support".  If the answer is "just ActiveRecord" then that's fine but to me that didn't feel like doing enough to allow ROM to slip into an existing project with minimal hassle.

**Comment by mjtko** [comment]
(Conversation ensued on Gitter: [February 20 2015 10:35 AM](https://gitter.im/rom-rb/chat?at=54e70dfb33f15015755cad0e))

**Comment by solnic** [comment]
Given that ROM can be easily set up using its interface I think we should abandon this idea. I'm going to close it and please yell at me if you disagree :)

**Pull request closed without merging**
