### PR TITLE
WIP Improved validators

### PR DESCRIPTION
**Pull request by solnic**
This is a significant improvement in params/validators API:

* [x] move validation DSL from params to validators
* [x] add support for validations that require database (like uniqueness)
* [x] come up with a common interface for adapters to check uniqueness of a given attribute

refs rom-rb/rom#101 rom-rb/rom#102

### CODE REVIEW

**Comment by mcls** [comment]
What would become the form object in this case? 
Does it require an extra object that's a simple wrapper around the params and validator?

I checked this out locally and it fails because the params object no longer has `model_name` (and `errors` probably)

**Comment by mcls** [comment]
You probably already have something planned to handle to forms,
but maybe it's interesting to see how I ended up implementing this :)

So here it goes:

```ruby
class RailsForm < Delegator
  extend ActiveModel::Naming
  include ActiveModel::Conversion

  attr_reader :errors

  def initialize(input, errors = nil)
    @input  = input
    @errors = errors || ActiveModel::Errors.new(input)
  end

  def __getobj__
    # Delegate to the ROM::Model::Params object
    @input
  end

  # Instantiate from a validation error
  #
  # @param [ROM::Model::ValidationError] error
  #
  # @return [RailsForm]
  def self.from_validation_error(error)
    self.new(error.params, error.messages)
  end
end
```

Still have to implement `#model_name` ...

```ruby
class Video
  class Form < RailsForm
    def model_name
      @model_name ||= ActiveModel::Name.new(Video)
    end
  end
end
```

And in the controller:

```ruby
class VideosController
  def new
    input = Video::Params.new
    render :new, locals: { video: Video::Form.new(input) }
  end

  def create
    attributes = params.require(:video).permit(:url)
    result = rom.command(:videos).try { create(attributes) }

    if result.error
      form = Video::Form.from_validation_error(result.error)
      render :new, locals: { video: form }
    else
      redirect_to :videos
    end
  end
end
```

**Comment by solnic** [comment]
Ah, thanks! It's really helpful to see how you tackled this.

Re "form objects" - my intention is not to provide any kind of form-object abstraction but to make param processing and validation error handling simple. You should be able to have a form object built on top of that (not even sure if you need it though) as a side-effect.

And yes, to make this work with form_for etc. we need a single object that gives both params and error messages. Currently in the branch we have `ValidatorError` which encapsulate both `params` and `errors` objects, so it's a matter of delegating attribute readers to the underlaying params.

**Comment by mcls** [comment]
Just to clarify: By form object I meant the object to be used with `form_for`. In the current release the `param` object could be used, but now it no longer responds to `model_name` and `errors`.

I created `RailsForm` to conform to this, but it would indeed be nice if that wasn't necessary.

**Comment by solnic** [comment]
Hah of course I forgot about the form rendering without errors...thanks, right, so...params and error objects must share common behavior required by AM to render stuff. I'll figure something out :)

**Comment by solnic** [comment]
@mcls ok [here's](https://github.com/rom-rb/rom-rails/blob/improved-validators/spec/dummy/app/models/user_form.rb) what I've come up with...thoughts?

**Comment by mcls** [comment]
Rails forms are mind bending, aren't they? :stuck_out_tongue: 

Setting of the `input` and `validations` does look nice this way.

 I was wondering why you didn't choose for setters like in the command definitions? (E.g. https://github.com/rom-rb/rom-rails/blob/master/spec/dummy/app/commands/users.rb#L3-L4)

Then the validator and param class can be reused.

**Comment by solnic** [comment]
@mcls re input/validator setters - I do plan to change it so that you can re-use standalone validator/params classes between commands and form-objects. I just started with the DSL :)

**Comment by solnic** [comment]
OK I made it...still needs a refactor before merging but I put together everything that is required to make it work with form_for and route helpers...here's how to use it:

``` ruby

**Comment by mcls** [comment]
Looks good from the outside :)

The Form also needs a `model_name` as a class method by the way. It failed for me when I used `:placeholder` on a text field.

It blew up on this line: 
https://github.com/rails/rails/blob/v4.2.0/actionview/lib/action_view/helpers/tags/placeholderable.rb#L15

**Comment by solnic** [comment]
Why isn't it calling `to_model.model_name`?!!?!? :((((( Iemme fix it on our side...

**Comment by solnic** [comment]
@mcls OK I added `model_name` to `Form` too

**Pull request merged**
